/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataRulesUpdateMetadataRule } from "../../funcs/metadataRulesUpdateMetadataRule.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateMetadataRuleRequest$inboundSchema,
};

export const tool$metadataRulesUpdateMetadataRule: ToolDefinition<typeof args> =
  {
    name: "update-metadata-rule",
    description: `Update metadata rule

Updates the properties and configuration of an existing metadata rule.`,
    scopes: ["builder"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await metadataRulesUpdateMetadataRule(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
