/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataFieldsRestoreMetadataFieldDatasource } from "../../funcs/metadataFieldsRestoreMetadataFieldDatasource.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RestoreMetadataFieldDatasourceRequest$inboundSchema,
};

export const tool$metadataFieldsRestoreMetadataFieldDatasource: ToolDefinition<
  typeof args
> = {
  name: "metadata-fields-restore-metadata-field-datasource",
  description: `Restore datasource values

Restores datasource values that have been deleted.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await metadataFieldsRestoreMetadataFieldDatasource(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
