/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataFieldsReorderMetadataFields } from "../../funcs/metadataFieldsReorderMetadataFields.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ReorderMetadataFieldsRequest$inboundSchema,
};

export const tool$metadataFieldsReorderMetadataFields: ToolDefinition<
  typeof args
> = {
  name: "metadata-fields-reorder-metadata-fields",
  description: `Reorder all metadata fields

Changes the display order of all metadata fields based on specified criteria.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metadataFieldsReorderMetadataFields(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
