/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataFieldsUpdateMetadataField } from "../../funcs/metadataFieldsUpdateMetadataField.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateMetadataFieldRequest$inboundSchema,
};

export const tool$metadataFieldsUpdateMetadataField: ToolDefinition<
  typeof args
> = {
  name: "update-metadata-field",
  description: `Update metadata field

Updates the properties and configuration of the specified metadata field.`,
  scopes: ["builder"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metadataFieldsUpdateMetadataField(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
