/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataFieldsSearchMetadataFieldDatasource } from "../../funcs/metadataFieldsSearchMetadataFieldDatasource.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SearchMetadataFieldDatasourceRequest$inboundSchema,
};

export const tool$metadataFieldsSearchMetadataFieldDatasource: ToolDefinition<
  typeof args
> = {
  name: "metadata-fields-search-metadata-field-datasource",
  description: `Search across all metadata field datasources

Performs a search across all metadata field datasources to find matching values.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metadataFieldsSearchMetadataFieldDatasource(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
