/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataFieldsSearchDatasourceInMDField } from "../../funcs/metadataFieldsSearchDatasourceInMDField.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SearchDatasourceInMDFieldRequest$inboundSchema,
};

export const tool$metadataFieldsSearchDatasourceInMDField: ToolDefinition<
  typeof args
> = {
  name: "metadata-fields-search-datasource-in-MD-field",
  description: `Search datasource values in a metadata field

Performs a search within a specific metadata field's datasource to find matching values, with support for exact or partial matches.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metadataFieldsSearchDatasourceInMDField(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
