/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataFieldsGetMetadataField } from "../../funcs/metadataFieldsGetMetadataField.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetMetadataFieldRequest$inboundSchema,
};

export const tool$metadataFieldsGetMetadataField: ToolDefinition<typeof args> =
  {
    name: "get-metadata-field",
    description: `Get metadata field

Retrieves detailed information about the specified metadata field.`,
    scopes: ["builder"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await metadataFieldsGetMetadataField(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
