/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataFieldsReorderMetadataField } from "../../funcs/metadataFieldsReorderMetadataField.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ReorderMetadataFieldRequest$inboundSchema,
};

export const tool$metadataFieldsReorderMetadataField: ToolDefinition<
  typeof args
> = {
  name: "metadata-fields-reorder-metadata-field",
  description: `Change position of metadata field

Changes the display position of a specific metadata field within the list.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metadataFieldsReorderMetadataField(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
