/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataFieldsListMetadataFields } from "../../funcs/metadataFieldsListMetadataFields.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListMetadataFieldsRequest$inboundSchema,
};

export const tool$metadataFieldsListMetadataFields: ToolDefinition<
  typeof args
> = {
  name: "list-metadata-fields",
  description: `Get metadata fields

Retrieves a list of all metadata fields in the product environment based on the provided filters.`,
  scopes: ["builder"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metadataFieldsListMetadataFields(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
