/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { streamingProfilesDeleteStreamingProfile } from "../../funcs/streamingProfilesDeleteStreamingProfile.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteStreamingProfileRequest$inboundSchema,
};

export const tool$streamingProfilesDeleteStreamingProfile: ToolDefinition<
  typeof args
> = {
  name: "delete-streaming-profile",
  description:
    `Delete custom streaming profile or revert built-in profile to the original settings`,
  scopes: ["builder"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await streamingProfilesDeleteStreamingProfile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
