/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { streamingProfilesGetStreamingProfiles } from "../../funcs/streamingProfilesGetStreamingProfiles.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetStreamingProfilesRequest$inboundSchema,
};

export const tool$streamingProfilesGetStreamingProfiles: ToolDefinition<
  typeof args
> = {
  name: "list-streaming-profiles",
  description: `Get streaming profiles`,
  scopes: ["builder"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await streamingProfilesGetStreamingProfiles(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
