/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transformationsListTransformations } from "../../funcs/transformationsListTransformations.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListTransformationsRequest$inboundSchema,
};

export const tool$transformationsListTransformations: ToolDefinition<
  typeof args
> = {
  name: "list-transformations",
  description: `Get transformations

Retrieves a list of all transformations, which can be filtered to show either only named or unnamed transformations.
`,
  scopes: ["builder"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transformationsListTransformations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
