/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transformationsDeleteTransformation } from "../../funcs/transformationsDeleteTransformation.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteTransformationRequest$inboundSchema,
};

export const tool$transformationsDeleteTransformation: ToolDefinition<
  typeof args
> = {
  name: "delete-transformation",
  description: `Delete a transformation

Delete a named or unnamed transformation. Optionally invalidate derived resources generated using the named transformation.
`,
  scopes: ["builder"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transformationsDeleteTransformation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
