/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { transformationsUpdateTransformation } from "../../funcs/transformationsUpdateTransformation.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  transformation: z.string(),
  updateRequest: components.UpdateRequest$inboundSchema,
};

export const tool$transformationsUpdateTransformation: ToolDefinition<
  typeof args
> = {
  name: "update-transformation",
  description: `Updates the definition of an existing named transformation

Update an existing named or unnamed transformation.
`,
  scopes: ["admin"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transformationsUpdateTransformation(
      client,
      args.transformation,
      args.updateRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
