/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transformationsUpdateTransformation } from "../../funcs/transformationsUpdateTransformation.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateTransformationRequest$inboundSchema,
};

export const tool$transformationsUpdateTransformation: ToolDefinition<
  typeof args
> = {
  name: "update-transformation",
  description: `Update a transformation

Update an existing named or unnamed transformation.
`,
  scopes: ["builder"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transformationsUpdateTransformation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
