/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uploadPresetsDeleteUploadPreset } from "../../funcs/uploadPresetsDeleteUploadPreset.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteUploadPresetRequest$inboundSchema,
};

export const tool$uploadPresetsDeleteUploadPreset: ToolDefinition<typeof args> =
  {
    name: "delete-upload-preset",
    description: `Deletes an upload preset`,
    scopes: ["builder"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await uploadPresetsDeleteUploadPreset(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
