/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uploadMappingsReplaceUploadMappings } from "../../funcs/uploadMappingsReplaceUploadMappings.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ReplaceUploadMappingsRequest$inboundSchema,
};

export const tool$uploadMappingsReplaceUploadMappings: ToolDefinition<
  typeof args
> = {
  name: "upload-mappings-replace-upload-mappings",
  description: `Replaces all upload mappings`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uploadMappingsReplaceUploadMappings(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
