/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uploadPresetsGetUploadPreset } from "../../funcs/uploadPresetsGetUploadPreset.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetUploadPresetRequest$inboundSchema,
};

export const tool$uploadPresetsGetUploadPreset: ToolDefinition<typeof args> = {
  name: "get-upload-preset-details",
  description: `Retrieves details of a single upload preset`,
  scopes: ["builder"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uploadPresetsGetUploadPreset(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
