/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { uploadPresetsUpdateUploadPreset } from "../../funcs/uploadPresetsUpdateUploadPreset.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  name: z.string(),
  uploadPreset: components.UploadPreset$inboundSchema,
};

export const tool$uploadPresetsUpdateUploadPreset: ToolDefinition<typeof args> =
  {
    name: "update-upload-preset",
    description: `Updates an existing upload preset's configuration settings`,
    scopes: ["builder"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await uploadPresetsUpdateUploadPreset(
        client,
        args.name,
        args.uploadPreset,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
