/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uploadMappingsDeleteUploadMapping } from "../../funcs/uploadMappingsDeleteUploadMapping.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteUploadMappingRequest$inboundSchema,
};

export const tool$uploadMappingsDeleteUploadMapping: ToolDefinition<
  typeof args
> = {
  name: "delete-upload-mapping",
  description: `Deletes an upload mapping

Permanently deletes the upload mapping for the specified folder`,
  scopes: ["builder"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uploadMappingsDeleteUploadMapping(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
