/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { CloudinaryConfigCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$metadataFieldsCreateMetadataField } from "./tools/metadataFieldsCreateMetadataField.js";
import { tool$metadataFieldsDeleteMetadataField } from "./tools/metadataFieldsDeleteMetadataField.js";
import { tool$metadataFieldsDeleteMetadataFieldDatasource } from "./tools/metadataFieldsDeleteMetadataFieldDatasource.js";
import { tool$metadataFieldsGetMetadataField } from "./tools/metadataFieldsGetMetadataField.js";
import { tool$metadataFieldsListMetadataFields } from "./tools/metadataFieldsListMetadataFields.js";
import { tool$metadataFieldsUpdateMetadataField } from "./tools/metadataFieldsUpdateMetadataField.js";
import { tool$metadataFieldsUpdateMetadataFieldDatasource } from "./tools/metadataFieldsUpdateMetadataFieldDatasource.js";
import { tool$metadataRulesCreateMetadataRule } from "./tools/metadataRulesCreateMetadataRule.js";
import { tool$metadataRulesDeleteMetadataRule } from "./tools/metadataRulesDeleteMetadataRule.js";
import { tool$metadataRulesListMetadataRules } from "./tools/metadataRulesListMetadataRules.js";
import { tool$metadataRulesUpdateMetadataRule } from "./tools/metadataRulesUpdateMetadataRule.js";
import { tool$streamingProfilesCreateStreamingProfile } from "./tools/streamingProfilesCreateStreamingProfile.js";
import { tool$streamingProfilesDeleteStreamingProfile } from "./tools/streamingProfilesDeleteStreamingProfile.js";
import { tool$streamingProfilesGetStreamingProfile } from "./tools/streamingProfilesGetStreamingProfile.js";
import { tool$streamingProfilesGetStreamingProfiles } from "./tools/streamingProfilesGetStreamingProfiles.js";
import { tool$streamingProfilesUpdateStreamingProfile } from "./tools/streamingProfilesUpdateStreamingProfile.js";
import { tool$transformationsCreateTransformation } from "./tools/transformationsCreateTransformation.js";
import { tool$transformationsDeleteTransformation } from "./tools/transformationsDeleteTransformation.js";
import { tool$transformationsGetTransformation } from "./tools/transformationsGetTransformation.js";
import { tool$transformationsListTransformations } from "./tools/transformationsListTransformations.js";
import { tool$transformationsUpdateTransformation } from "./tools/transformationsUpdateTransformation.js";
import { tool$triggersCreateTrigger } from "./tools/triggersCreateTrigger.js";
import { tool$triggersDeleteTrigger } from "./tools/triggersDeleteTrigger.js";
import { tool$triggersListTrigger } from "./tools/triggersListTrigger.js";
import { tool$triggersUpdateTrigger } from "./tools/triggersUpdateTrigger.js";
import { tool$uploadMappingsCreateUploadMapping } from "./tools/uploadMappingsCreateUploadMapping.js";
import { tool$uploadMappingsDeleteUploadMapping } from "./tools/uploadMappingsDeleteUploadMapping.js";
import { tool$uploadMappingsListUploadMappings } from "./tools/uploadMappingsListUploadMappings.js";
import { tool$uploadMappingsUpdateUploadMapping } from "./tools/uploadMappingsUpdateUploadMapping.js";
import { tool$uploadPresetsCreateUploadPreset } from "./tools/uploadPresetsCreateUploadPreset.js";
import { tool$uploadPresetsDeleteUploadPreset } from "./tools/uploadPresetsDeleteUploadPreset.js";
import { tool$uploadPresetsGetUploadPreset } from "./tools/uploadPresetsGetUploadPreset.js";
import { tool$uploadPresetsListUploadPresets } from "./tools/uploadPresetsListUploadPresets.js";
import { tool$uploadPresetsUpdateUploadPreset } from "./tools/uploadPresetsUpdateUploadPreset.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  cloudName?: SDKOptions["cloudName"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
  defaultHost?: SDKOptions["defaultHost"] | undefined;
}) {
  const server = new McpServer({
    name: "CloudinaryConfig",
    version: "0.2.1",
  });

  const client = new CloudinaryConfigCore({
    security: deps.security,
    cloudName: deps.cloudName,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
    defaultHost: deps.defaultHost,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$transformationsListTransformations);
  tool(tool$transformationsGetTransformation);
  tool(tool$transformationsCreateTransformation);
  tool(tool$transformationsUpdateTransformation);
  tool(tool$transformationsDeleteTransformation);
  tool(tool$uploadPresetsCreateUploadPreset);
  tool(tool$uploadPresetsListUploadPresets);
  tool(tool$uploadPresetsGetUploadPreset);
  tool(tool$uploadPresetsUpdateUploadPreset);
  tool(tool$uploadPresetsDeleteUploadPreset);
  tool(tool$metadataFieldsCreateMetadataField);
  tool(tool$metadataFieldsListMetadataFields);
  tool(tool$metadataFieldsGetMetadataField);
  tool(tool$metadataFieldsUpdateMetadataField);
  tool(tool$metadataFieldsDeleteMetadataField);
  tool(tool$metadataFieldsUpdateMetadataFieldDatasource);
  tool(tool$metadataFieldsDeleteMetadataFieldDatasource);
  tool(tool$metadataRulesCreateMetadataRule);
  tool(tool$metadataRulesListMetadataRules);
  tool(tool$metadataRulesUpdateMetadataRule);
  tool(tool$metadataRulesDeleteMetadataRule);
  tool(tool$uploadMappingsListUploadMappings);
  tool(tool$uploadMappingsCreateUploadMapping);
  tool(tool$uploadMappingsUpdateUploadMapping);
  tool(tool$uploadMappingsDeleteUploadMapping);
  tool(tool$triggersListTrigger);
  tool(tool$triggersCreateTrigger);
  tool(tool$triggersUpdateTrigger);
  tool(tool$triggersDeleteTrigger);
  tool(tool$streamingProfilesCreateStreamingProfile);
  tool(tool$streamingProfilesGetStreamingProfiles);
  tool(tool$streamingProfilesGetStreamingProfile);
  tool(tool$streamingProfilesUpdateStreamingProfile);
  tool(tool$streamingProfilesDeleteStreamingProfile);

  return server;
}
