/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { MetadataFields } from "./metadatafields.js";
import { MetadataRules } from "./metadatarules.js";
import { StreamingProfiles } from "./streamingprofiles.js";
import { Transformations } from "./transformations.js";
import { Triggers } from "./triggers.js";
import { UploadMappings } from "./uploadmappings.js";
import { UploadPresets } from "./uploadpresets.js";

export class CloudinaryConfig extends ClientSDK {
  private _transformations?: Transformations;
  get transformations(): Transformations {
    return (this._transformations ??= new Transformations(this._options));
  }

  private _uploadPresets?: UploadPresets;
  get uploadPresets(): UploadPresets {
    return (this._uploadPresets ??= new UploadPresets(this._options));
  }

  private _metadataFields?: MetadataFields;
  get metadataFields(): MetadataFields {
    return (this._metadataFields ??= new MetadataFields(this._options));
  }

  private _metadataRules?: MetadataRules;
  get metadataRules(): MetadataRules {
    return (this._metadataRules ??= new MetadataRules(this._options));
  }

  private _uploadMappings?: UploadMappings;
  get uploadMappings(): UploadMappings {
    return (this._uploadMappings ??= new UploadMappings(this._options));
  }

  private _triggers?: Triggers;
  get triggers(): Triggers {
    return (this._triggers ??= new Triggers(this._options));
  }

  private _streamingProfiles?: StreamingProfiles;
  get streamingProfiles(): StreamingProfiles {
    return (this._streamingProfiles ??= new StreamingProfiles(this._options));
  }
}
