/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { triggersCreateTrigger } from "../funcs/triggersCreateTrigger.js";
import { triggersDeleteTrigger } from "../funcs/triggersDeleteTrigger.js";
import { triggersListTrigger } from "../funcs/triggersListTrigger.js";
import { triggersUpdateTrigger } from "../funcs/triggersUpdateTrigger.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Triggers extends ClientSDK {
  /**
   * Get event triggers
   *
   * @remarks
   * Retrieves a list of all event triggers and notifications within your product environment.
   */
  async listTrigger(
    request: operations.ListTriggerRequest,
    options?: RequestOptions,
  ): Promise<operations.ListTriggerResponse> {
    return unwrapAsync(triggersListTrigger(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a trigger
   *
   * @remarks
   * Creates a new trigger.
   * Your product environment supports triggers up to a maximum determined by multiplying the number of unique event types by the limit of 30 notification URLs.
   */
  async createTrigger(
    request: operations.CreateTriggerRequest,
    options?: RequestOptions,
  ): Promise<components.TriggerInfo> {
    return unwrapAsync(triggersCreateTrigger(
      this,
      request,
      options,
    ));
  }

  /**
   * Update trigger URL
   *
   * @remarks
   * Updates a notification URL for a trigger.
   */
  async updateTrigger(
    request: operations.UpdateTriggerRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateTriggerResponse> {
    return unwrapAsync(triggersUpdateTrigger(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a trigger
   *
   * @remarks
   * Deletes a trigger.
   */
  async deleteTrigger(
    request: operations.DeleteTriggerRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteTriggerResponse> {
    return unwrapAsync(triggersDeleteTrigger(
      this,
      request,
      options,
    ));
  }
}
