/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const UriType = {
  Webhook: "webhook",
  Flow: "flow",
} as const;
export type UriType = ClosedEnum<typeof UriType>;

/** @internal */
export const UriType$inboundSchema: z.ZodNativeEnum<typeof UriType> = z
  .nativeEnum(UriType);

/** @internal */
export const UriType$outboundSchema: z.ZodNativeEnum<typeof UriType> =
  UriType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UriType$ {
  /** @deprecated use `UriType$inboundSchema` instead. */
  export const inboundSchema = UriType$inboundSchema;
  /** @deprecated use `UriType$outboundSchema` instead. */
  export const outboundSchema = UriType$outboundSchema;
}
